clear all
close all

% User Input Code Section
% Input TDIP filename
filename = 'H3C\S11T\S11_TDIP_1Hz_Z.xlsx';


% Main Code Section
[num, txt] = xlsread(filename);

t = zeros(1, 1000);
Va = zeros(1, 1000);
Vm = zeros(1, 1000);
Vn = zeros(1, 1000);
Vb = zeros(1, 1000);

for i = 1:1000
    t(i) = num(i, 1);
    Va(i) = num(i, 2);
    Vm(i) = num(i, 3);
    Vn(i) = num(i, 4);
    Vb(i) = num(i, 5);
end

fig = figure('Units', 'pixels', ...
    'Position', [200 200 500 375]);
set(fig, ...
    'Color',        'w');

subplot(2, 1, 1)
hold on
box on

vaPlotA = line(t, Va, 'DisplayName', 'Va');
vbPlotA = line(t, Vb, 'DisplayName', 'Vb');

vppLine = line([0.2, 0.3], [0.7193, 0.7193]);
vspLine = line([0.1, 0.2], [0.08164, 0.08164]);

vpmLine = line([0.7, 0.8], [-0.6955, -0.6955]);
vsmLine = line([0.6, 0.7], [-0.05386, -0.05386]);

set([vppLine, vspLine, vpmLine, vsmLine], ...
    'LineStyle',        '--', ...
    'Color', 'k');

legend([vaPlotA, vbPlotA], 'V_a', 'V_b')

xlim([0, 1])
xticks([0.0, 0.2, 0.4, 0.6, 0.8, 1.0])
ylim([-0.8, 0.8])
yticks([-0.8, -0.4, 0, 0.4, 0.8])

TitleA = title('$V_a$ and $V_b$', 'Interpreter', 'latex');
XLabelA = ylabel('Voltage ($V$)', 'Interpreter', 'latex');
YLabelA = xlabel('Time ($s$)', 'Interpreter', 'latex');

set(gca, ...
    'FontName',     'Arial', ...
    'FontSize',     10, ...
    'XScale',       'linear', ...
    'Box',          'on', ...
    'TickDir',      'in', ...
    'TickLength',   [.02 .02], ...
    'XMinorTick',   'on', ...
    'YMinorTick',   'off', ...
    'YGrid',        'on', ...
    'GridLineStyle',':', ...
    'GridColor',    'k', ...
    'GridAlpha',    0.5, ...
    'LineWidth',    1);

set([TitleA, XLabelA, YLabelA], ...
    'FontName',     'Arial');
set([XLabelA, YLabelA], ...
    'FontSize',     10);
set(TitleA, ...
    'FontSize',     12, ...
    'FontWeight',   'bold');

set(vaPlotA, ...
    'LineStyle',        '-', ...
    'Color', 'r');

set(vbPlotA, ...
    'LineStyle',        '-', ...
    'Color', 'b');

subplot(2, 1, 2)
hold on
box on

vaPlotB = line(t, Va);
vmnPlotB = line(t, Vm - Vn);

vpLine = line([0.2, 0.3], [0.33, 0.33]);
vmLine = line([0.7, 0.8], [-0.33, -0.33]);

set([vpLine, vmLine], ...
    'LineStyle',        '--', ...
    'Color', 'k');

legend([vaPlotB, vmnPlotB], 'V_a', 'V_{mn}')

xlim([0, 1])
xticks([0.0, 0.2, 0.4, 0.6, 0.8, 1.0])
ylim([-0.6, 0.6])
yticks([-0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6])

TitleB = title('$V_a$ and $V_{mn}$', 'Interpreter', 'latex');
XLabelB = ylabel('Voltage ($V$)', 'Interpreter', 'latex');
YLabelB = xlabel('Time ($s$)', 'Interpreter', 'latex');

set(gca, ...
    'FontName',     'Arial', ...
    'FontSize',     10, ...
    'XScale',       'linear', ...
    'Box',          'on', ...
    'TickDir',      'in', ...
    'TickLength',   [.02 .02], ...
    'XMinorTick',   'on', ...
    'YMinorTick',   'off', ...
    'YGrid',        'on', ...
    'GridLineStyle',':', ...
    'GridColor',    'k', ...
    'GridAlpha',    0.5, ...
    'LineWidth',    1);

set([TitleB, XLabelB, YLabelB], ...
    'FontName',     'Arial');
set([XLabelB, YLabelB], ...
    'FontSize',     10);
set(TitleB, ...
    'FontSize',     12, ...
    'FontWeight',   'bold');

set(vaPlotB, ...
    'LineStyle',        '-', ...
    'Color', 'r');

set(vmnPlotB, ...
    'LineStyle',        '-', ...
    'Color', 'b');

tIntp = zeros(1, 250-102+1);
VbIntp = zeros(1, 250-102+1);
tIntm = zeros(1, 500-352+1);
VbIntm = zeros(1, 500-352+1);
j = 1;
for i = 102:250
    tIntp(j) = t(i);
    VbIntp(j) = Vb(i);
    j = j + 1;
end

j = 1;
for i = 352:500
    tIntm(j) = t(i);
    VbIntm(j) = Vb(i);
    j = j + 1;
end

fig = figure('Units', 'pixels', ...
    'Position', [200 200 500 375]);
set(fig, ...
    'Color',        'w');
subplot(2, 1, 1)

lineP = line(tIntp, VbIntp);

xlim([0.2, 0.5])
xticks([0.2, 0.3, 0.4, 0.5])
ylim([0, 0.2])
yticks([0, 0.05, 0.1, 0.15, 0.2])

TitleC = title('$V_b$ Decay in Positive Cycle', 'Interpreter', 'latex');
XLabelC = ylabel('Voltage ($V$)', 'Interpreter', 'latex');
YLabelC = xlabel('Time ($s$)', 'Interpreter', 'latex');

set(gca, ...
    'FontName',     'Arial', ...
    'FontSize',     10, ...
    'XScale',       'linear', ...
    'Box',          'on', ...
    'TickDir',      'in', ...
    'TickLength',   [.02 .02], ...
    'XMinorTick',   'on', ...
    'YMinorTick',   'off', ...
    'YGrid',        'on', ...
    'GridLineStyle',':', ...
    'GridColor',    'k', ...
    'GridAlpha',    0.5, ...
    'LineWidth',    1);

set([TitleC, XLabelC, YLabelC], ...
    'FontName',     'Arial');
set([XLabelC, YLabelC], ...
    'FontSize',     10);
set(TitleC, ...
    'FontSize',     12, ...
    'FontWeight',   'bold');

set(lineP, ...
    'LineStyle',        'none', ...
    'Marker',           '.', ...
    'MarkerEdgeColor',   'k', ...
    'MarkerFaceColor',  [.7 .7 .7]);

subplot(2, 1, 2)
lineM = line(tIntm, VbIntm);

xlim([0.7, 1.0])
xticks([0.7, 0.8, 0.9, 1.0])
ylim([-0.2, 0])
yticks([-0.2, -0.15, -0.1, -0.05, 0])

TitleD = title('$V_b$ Decay in Negative Cycle', 'Interpreter', 'latex');
XLabelD = ylabel('Voltage ($V$)', 'Interpreter', 'latex');
YLabelD = xlabel('Time ($s$)', 'Interpreter', 'latex');

set(gca, ...
    'FontName',     'Arial', ...
    'FontSize',     10, ...
    'XScale',       'linear', ...
    'Box',          'on', ...
    'TickDir',      'in', ...
    'TickLength',   [.02 .02], ...
    'XMinorTick',   'on', ...
    'YMinorTick',   'off', ...
    'YGrid',        'on', ...
    'GridLineStyle',':', ...
    'GridColor',    'k', ...
    'GridAlpha',    0.5, ...
    'LineWidth',    1);

set([TitleD, XLabelD, YLabelD], ...
    'FontName',     'Arial');
set([XLabelD, YLabelD], ...
    'FontSize',     10);
set(TitleD, ...
    'FontSize',     12, ...
    'FontWeight',   'bold');

set(lineM, ...
    'LineStyle',        'none', ...
    'Marker',           '.', ...
    'MarkerEdgeColor',   'k', ...
    'MarkerFaceColor',  [.7 .7 .7]);